#webrtc setup
repositories:
# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

- name: jetstack
  url: https://charts.jetstack.io

- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  # Published chart example
  - name: "cert-manager"                            # name of this release
    namespace: "cert-manager"                       # target namespace
    chart: "jetstack/cert-manager"
    createNamespace: true  # for helm >3.2
    version: 0.15.1


  - name: "dev"
    namespace: "nginx"
    chart: "bitnami/nginx-ingress-controller"
    createNamespace: true  # for helm >3.2
    version: 5.3.24
# todo remove old one and make bitnami the main

  - name: "first"
    namespace: "first"
    chart: "../new/docker-jitsi-meet/examples/helm"
    createNamespace: true  # for helm >3.2
    values:
      - jvb:
          service:
            type: NodePort
          UDPPort: 30000
          TCPPort: 30443
          publicIP: 35.228.209.133
      - web:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: "letsencrypt"
            hosts:
            - host: test.ceon.xyz
              paths: ['/']
            tls:
            - secretName: jitsi-web-certificate
              hosts:
               - test.ceon.xyz
      - jvb:
          xmpp:
            user: focus
            password: someSensativePassword
            componentSecret: SomeSensatiValue
      - jicofo:
          xmpp:
            user: focus
            password: someSensativePassword
            componentSecret: SomeSensatiValue
